apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-development
  namespace: development
spec:
  selector:
    matchLabels:
      app: keycloak-development
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: keycloak-development
    spec:
      containers:
      - name: keycloak-development
        image: quay.io/keycloak/keycloak:20.0.5
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://Mykeycloak-development/auth/"
        - name: KEYCLOAK_ADMIN_URL
          value: "https://Mykeycloak-development/auth/realms/master/admin/"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        command:
        - "/opt/keycloak/bin/kc.sh"
        args:
        - "start-dev"
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 280
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
