apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 3
  labels:
    app: key-sso
  name: key-sso
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: key-sso
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: key-sso
    spec:
      containers:
      - args:
        - start-dev
        command:
        - /opt/keycloak/bin/kc.sh
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: PROXY_ADDRESS_FORWARDING
        - name: KEYCLOAK_FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KEYCLOAK_FRONTEND_URL
        - name: KEYCLOAK_ADMIN_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KEYCLOAK_ADMIN_URL
        image: quay.io/keycloak/keycloak:20.0.5
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
