apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: development
    name: local-pvc
  hostPath:
    path: /mnt/data
